clusters:
    example.com:
        baseURL: "https:/www.example.com"
        username: "user"
        password: "pass"
        client_id: "myID"

        pkcs12_file_url: "http://www.example.com/certs/cert.pfx"
        pkcs12_file_path: "/var/www/html/certs/cert.pfx"
        pkcs12_passphrase: "pass"
