clusters:
    example.com:
        baseURL: "https://example.com"
        username: "user"
        password: "pass"
        client_id: "myClient"

        pkcs12_file_url: "192.168.1.1/certs/mycert.pfx"
        pkcs12_passphrase: "pass"